on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        graphwalker-version: [ 'latest', '4.3.1', '' ]

    steps:
      - name: Setup GraphWalker ${{ matrix.graphwalker-version }}
        uses: altwalker/setup-graphwalker@main
        with:
          graphwalker-version: ${{ matrix.graphwalker-version }}
      - name: Run GraphWalker
        run: |
          gw --version

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Setup GraphWalker
        uses: altwalker/setup-graphwalker@main
      - name: Run GraphWalker
        run: |
          gw --version

  test-windows:
    runs-on: windows-latest

    steps:
      - name: Setup GraphWalker
        uses: altwalker/setup-graphwalker@main
      - name: Run GraphWalker
        run: |
          gw --version
